// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_ZQeEq9e4Hpj9TZ1_6qRDxSIJzyWAMQ',
    appId: '1:29728154817:web:35fb81e7f7b6425a3fa040',
    messagingSenderId: '29728154817',
    projectId: 'quiz-up-c1312',
    authDomain: 'quiz-up-c1312.firebaseapp.com',
    storageBucket: 'quiz-up-c1312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbUWyM4E_IJWXxvYc0Vn6sAFLimF8rww',
    appId: '1:29728154817:android:23e364deb3ec8d003fa040',
    messagingSenderId: '29728154817',
    projectId: 'quiz-up-c1312',
    storageBucket: 'quiz-up-c1312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcA0g_MRAh1hJvPe3FMgHDd537GSVl93c',
    appId: '1:29728154817:ios:9d4079abf56e429b3fa040',
    messagingSenderId: '29728154817',
    projectId: 'quiz-up-c1312',
    storageBucket: 'quiz-up-c1312.firebasestorage.app',
    iosBundleId: 'com.quizapp.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_ZQeEq9e4Hpj9TZ1_6qRDxSIJzyWAMQ',
    appId: '1:29728154817:web:f3448bf01e1225ae3fa040',
    messagingSenderId: '29728154817',
    projectId: 'quiz-up-c1312',
    authDomain: 'quiz-up-c1312.firebaseapp.com',
    storageBucket: 'quiz-up-c1312.firebasestorage.app',
  );
}
